services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # web console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  miniodb:
    image: postgres:latest
    container_name: miniodb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: miniodb
    ports:
      - "5432:5432"
    volumes:
      - miniodb_data:/var/lib/postgresql/data

volumes:
  minio_data:
    driver: local
  miniodb_data:
    driver: local